### ISSUE TITLE
Consider using revisions

### ISSUE THREAD

**Issue by phadej** [chordify/haskell-servant-pagination#11]
Both 2.2.1 and 2.2.2 releases:
- Are unnecessary large versions indicating (according to https://pvp.haskell.org/) that there are interface additions, that's not the case. Both could been 2.2.0.1 or 2.2.0.2
- Even so, the new releases are unnecessary, and bound alterations could been done using [revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md)

**Comment by KtorZ** [comment]
Indeed! My bad, and I am even more guilty because I knew about revisions already :( .. This hasn't become a habit yet, but that's a good reminder.
